number1=int(input("Enter number 1\n"))
number2=int(input("Enter number 2\n"))
add=int(number1)+int(number2)
print("Addition is {}".format(add))
power=number1**number2
print("power is ",power)
print("Subtraction is ",int(number1-number2))
print("multiplication is ",int(number1*number2))
print("remainder is ",int(number2%number1))
print("Quotient is ",number2/number1)
