number1=int(input("Enter number 1\n"))
number2=int(input("Enter number 2\n"))
number3=int(input("Enter number 3\n"))
add=int(number2)+int(number1)+int(number3)
print("Addition is {}".format(add))
power=number2**number1
print("power is ",power)
print("Subtraction is ",int(number2-number1-number3))
print("multiplication is ",int(number2*number1*number3))
print("remainder is ",int(number1%number2))
print("Quotient is ",number1/number2)
